# Generated by Django 4.2.5 on 2023-10-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.CharField(blank=True, max_length=250)),
                ('category', models.CharField(max_length=50)),
                ('top_sel_month', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('in_stock', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('self_delivery', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('description', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
