# Generated by Django 4.2.5 on 2023-10-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_description_goods_description1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.IntegerField(default=1000),
        ),
    ]
